### ISSUE TITLE
New spell - Dancing Lights

### ISSUE THREAD

**Issue by Taseabridge** [itteerde/fvttconfig#121]
You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can also combine the four lights into one glowing vaguely humanoid form of Medium size. Whichever form you choose, each light sheds dim light in a 10-foot radius.

As a bonus action on your turn, you can move the lights up to 60 feet to a new spot within range. A light must be within 20 feet of another light created by this spell, and a light winks out if it exceeds the spell's range.

**Comment by Taseabridge** [comment]
Found other way to handle inside the game

**Comment by itteerde** [comment]
no more light items, we will drop the others, not make new ones
