### ISSUE TITLE
Compendium Maintenance 

### ISSUE THREAD

**Issue by PhDaveMil** [itteerde/fvttconfig#168]
* Bless
* Divine Smite
* Aura of Vitality
* Spirit Shroud

**Comment by itteerde** [comment]
Do we want light source Actors? If so we still drop the current ones (is there even the supporting code in Module anymore?) and make new ones that would just put the light on Token and not modify Actor -- so no synchronization, keep it simple.

**Comment by itteerde** [comment]
dublicate
