### ISSUE TITLE
EB migration

### ISSUE THREAD

**Issue by itteerde** [itteerde/fvttconfig#197]
EB migration

- [x] backup
- [x] have 2.4.1 version available @itteerde 
- [x] uninstall `effective-transferral`
- [x] install [effectivetray](https://github.com/etiquettestartshere/effectivetray) [manifest (copy link address)](https://github.com/etiquettestartshere/effectivetray/releases/latest/download/module.json) #212 .
- [x] update system
- [x] update all modules
- [x] start world F-12 (patience)
- [x] switch CharacterSheet
- [x] Settings
  - [x] Encumbrance Tracking: Variant.
  - [x] Disable Expericence Tracking.
- [x] #231
- [x] #223
- [x] #224
- [x] #225
- [x] #226
- [x] #227
- [x] #228
- [x] #229
- [x] DDBI munching update (including character stuff [to get higher quality for future level-up imports)
- [x] Macros, incl. 
  - [x] UpdateInitiative [repo](https://github.com/itteerde/fvttconfig/blob/main/tools/macros/gm/UpdateInitiative.js)

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/fvttconfig/assets/8367477/516a6c2d-d909-41c9-a48a-ed093d1a75a9)

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/fvttconfig/assets/8367477/1107f194-cab3-4a93-8078-f9b0086961c3)

**Comment by itteerde** [comment]
Error: Actor5e [DHOGiVhKqsHpvmYd] validation errors:
![image](https://github.com/itteerde/fvttconfig/assets/8367477/4c33dea7-f1b6-4bd9-aa3a-bd98c87aa762)

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/fvttconfig/assets/8367477/5dc00541-54e3-4e81-981f-2e5768ae4b07)

**Comment by itteerde** [comment]
Error: Actor5e [Yr3h1fRpPEz8jesR] validation errors:

![image](https://github.com/itteerde/fvttconfig/assets/8367477/1043d2be-5a8e-4d0c-8669-ee81da6fa63d)

**Comment by itteerde** [comment]
Old `ActiveEffect`s might have the old data format, and might not have been migrated (?). Those should fail in v13. This does not need to be a priority, as with having the v12 preview 2 these days v13 will probably not be adopted for EB. Where it is caught we should still remake those items (not sure how to migrate by hand, not sure it is worth checking) to get rid of warnings that might hide important ones.

**Comment by PhDaveMil** [comment]
<img width="421" alt="image" src="https://github.com/itteerde/fvttconfig/assets/148652003/0048cb0f-281e-41fd-99a2-f5e525c4cfb7">

**Comment by PhDaveMil** [comment]
<img width="424" alt="image" src="https://github.com/itteerde/fvttconfig/assets/148652003/027602c4-353f-4686-89fa-cd8ef3fe2371">

**Comment by PhDaveMil** [comment]
This happened on a DDB Import:

<img width="407" alt="image" src="https://github.com/itteerde/fvttconfig/assets/148652003/513e5ef5-9396-41d4-8807-732a739115e1">
