### ISSUE TITLE
Feature Item Organization Categories 

### ISSUE THREAD

**Issue by PhDaveMil** [itteerde/fvttconfig#233]
While new characters imported via Beyond properly organize features into "class," "race," and "other," older imported character mass organize everything under "other." This must be fixed, but might need to be fixed on my end by rebuilding characters. Please, check if there is an easier way to fix the issue before I spend the time rebuilding characters and then advise me as to the best/easiest fix. We should fix this problem by the time characters are hitting their next level (4 for RotFM), for if I have to rebuild characters, I will do so when I next level the party.

**Comment by itteerde** [comment]
```js
let guy = game.actors.find(a=>a.name.startsWith("Gorun"));
let gial = game.actors.find(a=>a.name.startsWith("Gial"));
guy.items.filter(i=>i.type==="feat");
gial.items.filter(i=>i.type==="feat");
```
as expected.

**Comment by itteerde** [comment]
imported a new Gial

```js
let ar = gial.items.find(i=>i.name="Arcane Recovery");
let ar2 = gial2.items.find(i=>i.name="Arcane Recovery");
foundry.utils.diffObject(ar,ar2);
```

**Comment by itteerde** [comment]
- https://discord.com/channels/170995199584108546/670336046164213761/1224434777352835073

**Comment by itteerde** [comment]
oh my: https://github.com/foundryvtt/dnd5e/issues/2837

**Comment by itteerde** [comment]
Need to discuss @PhDaveMil

**Comment by itteerde** [comment]
```js
const x = actor.items.getName("Your Feature's Name");
const y = actor.items.getName("Class/Subclass/Race/Background Name");
await x.setFlag("dnd5e", "advancementOrigin", y.id);
```
https://discord.com/channels/170995199584108546/670336046164213761/1224852248782442516

**Comment by itteerde** [comment]
might need to use the ID as GM

```js
const actor = game.actors.get("OjnPpDlwJNVcrNWH"); //id
const x = actor.items.getName("Legacy of Stygia");
const y = actor.items.getName("Levistus Tiefling (Legacy)");
await x.setFlag("dnd5e", "advancementOrigin", y.id);
```
