### ISSUE TITLE
Please examine Forgotten Adventures Battlemaps and Monk's Active Tile Triggers

### ISSUE THREAD

**Issue by PhDaveMil** [itteerde/fvttconfig#238]
I am considering acquiring the following for our games: https://foundryvtt.com/packages/fa-battlemaps. I need someone to look over it and check whether it is a safe acquisition for us. If so, I think it would help me reduce some prep time while improving our overall quality of life for our homebrew games (Spelljammer and Eclipse Phase are the two that I think would benefit from it).

**Comment by itteerde** [comment]
What questions do you have?
