### ISSUE TITLE
Extended Rest Macro

### ISSUE THREAD

**Issue by PhDaveMil** [itteerde/fvttconfig#253]
Require an Extended Rest macro for the purpose of regaining HD.

**Comment by itteerde** [comment]
- https://github.com/itteerde/fvttconfig/blob/main/macros/gm/HitDiceRecovery.js

**Comment by PhDaveMil** [comment]
I am an idiot. The Long Rest recovery and Extended Rest HD recovery macros should be a single combined macro used whenever the group takes an extended rest, as both are a function of the Extended Rest.

**Comment by itteerde** [comment]
Back to just HitDiceRecovery

**Comment by itteerde** [comment]
delete, back to Rules
