### ISSUE TITLE
Shifting does not grant tempHP

### ISSUE THREAD

**Issue by itteerde** [itteerde/fvttconfig#3]
does not.

**Comment by itteerde** [comment]
Reproduce on own FVTT, probably export custom effects from DFreds as JSON, get DDB link for the character, import both custom effects and the character locally. Once that works pleas put the information needed to reproduce in here (there is drag and drop support right here in case there is indedd a JSON export available.

**Comment by itteerde** [comment]
The first version we have with the `Macro` rolling for the `Temp HP`, them applying per hand, DFreds setting the `AC+1` `Effect` is acceptable but not good. Imporving it a bit by setting automatically but having a bit of a struggle with DFreds being automated is mybe somewhat better, but in the end it should use methods from the `Stress` `Macro` to define, set and remove the whole `Effect`.

[Issue for Stess](https://github.com/itteerde/fvttconfig/issues/17)

**Comment by itteerde** [comment]
DFreds and a `Macro`, not nice but works. Can improve later.

**Comment by itteerde** [comment]
We should have proper Shifting for all option, 
+ Beasthide
+ Longtooth
+ Swiftstride
+ Wildhunt
with all their traits.
![image](https://user-images.githubusercontent.com/8367477/200694104-0d6eefb4-d2ac-43d2-b2f6-129d390c7d13.png)

**Comment by itteerde** [comment]
A Shifter picks what they get at character creation. So noch chosing and no multiple `Feat` `Items`. So maybe not making all right now, but the current version is still bad, as it does not even consume the resource.

Make it a `Item Macro` using the `Shifting: Beasthide` `Feat` `Item` created by `DDB-Importer`.

**Comment by Taseabridge** [comment]
Resolved with v0.0.10-0.0.11.

**Comment by itteerde** [comment]
put corrected Macro (abort on failed use) on the item in the Compendium.

**Comment by itteerde** [comment]
Accepted.
