### ISSUE TITLE
Summon Beast

### ISSUE THREAD

**Issue by Taseabridge** [itteerde/fvttconfig#66]
Summon Beast spell has 3 forms that can be summoned.
There is no working character sheet for the "Bestial Spirit" in the compendium. 

When the bestial spirit is summoned, the AC, HP, number of attacks and Weapon damage are all based on the "Spells Level", while the Weapon Attack Modifier is based on the "Spell Attack Modifier" of the caster, and Proficiency Bonus of the creature is equal to the casters.

**Comment by itteerde** [comment]
https://www.dndbeyond.com/spells/summon-beast

**Comment by itteerde** [comment]
Requestor ChatMessage. GM, once, image.

**Comment by Taseabridge** [comment]
Summon Beast, as well as other Summon Spells, have been added.
