### ISSUE TITLE
Music not playing - With error

### ISSUE THREAD

**Issue by Taseabridge** [itteerde/fvttconfig#71]
![image](https://user-images.githubusercontent.com/115514789/206266470-72614bf5-51d0-44f3-939c-90206c3b0eaf.png)

**Comment by itteerde** [comment]
![image](https://user-images.githubusercontent.com/8367477/209757100-e6fc69ac-7f1c-4a4a-a3ba-4802b0baa2a7.png)

**Comment by itteerde** [comment]
probably can't fix with any reasonable effort and maintainability
