### ISSUE TITLE
Regeneration

### ISSUE THREAD

**Issue by itteerde** [itteerde/fvttconfig#74]
sure, Effect-Macro. should just be
```js
actor.applyDamage(-10);
```
and you would toggle instead of deleting it if hit by preventing stuff. Yeah, works.

and you would toggle instead of deleting it if hit by preventing stuff. Yeah, works. 
which brings me to @Taseabridge  (mainly): anything FVTT to be done this weekend?
but one would have to toggle it back on this way. but everything past that (unless I am missing something) would become a bit more involved, though maybe worth it (a macro that adds a second effect that prevents the healing for one turn [and then just goes away because its duration is only one turn therefore letting the regeneration effect work again], think you would like to have that when setting up CoS) 
Yeah, I think there should be a generic pair of
- Regeneration (Effect-Macro you put onto whomever can regenerate)
- ControlBar Macro for putting a Stop-Regeneration Effect onto Selected Token's Actor for one Turn.

**Comment by Tak** [comment]
Uh… wrong Tak?

**Comment by itteerde** [comment]
> 

funny. That is copied straight out of discord. Yeah, not you.

**Comment by itteerde** [comment]
seems to work.
