### ISSUE TITLE
Initialize a cloud test environment

### ISSUE THREAD

**Issue by shaneguignard** [itteerde/fvttconfig#8]
Architect a test/dev environment that will enable contributors to work on their changes without effecting production instance

**Comment by shaneguignard** [comment]
https://foundryvtt.wiki/en/setup/hosting/always-free-oracle#h-optional-s3-storage-setup

Says that we might be sailing on our own here boys. 

![image](https://user-images.githubusercontent.com/42676358/197925905-9dee9f2f-5275-498e-af2d-438e7e8256b2.png)

**Comment by itteerde** [comment]
I think lokal storage (or what looks like it) will certainly be fine for the running server. If alternative currently not running servers would extend the size that comes with it I am not sure. But in the AWS case the EC2 instance has at least 8GB attached. That would be quite some reserves if it wasn't for the audio. With the audio the production instance is over 3GB after install. If the audio can be shared still no problem. If not the minimum sice would not be enough, but I have not checked what in the AWS case would be the extension paths. I doubt full bells and whistles storage cloud is the only path right from very low sizes. But I would have to check that.

**Comment by itteerde** [comment]
should it really be something without a local filesystem (seemingly working like local hd) this might be useful

https://github.com/krbz999/zhell-macros/blob/main/tools/image_migration_tool_PREPEND.js

**Comment by itteerde** [comment]
With our instance sizes we can not move to any cloud without causing excessive costs.
